# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
#RUN npm run build

ARG FRONTEND_PORT

# Expose the port the app runs on
EXPOSE $FRONTEND_PORT

# Start the application
CMD ["npm", "run", "serve", "-- --port", "$FRONTEND_PORT"]